# See https://github.com/rust-lang/cargo/issues/3946#issuecomment-973132993
# and https://doc.rust-lang.org/cargo/reference/config.html#env
[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }
